"""add-redis

Revision ID: b83101fb6589
Revises: bccef047ad1a
Create Date: 2025-11-10 12:55:19.022353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83101fb6589'
down_revision: Union[str, None] = 'bccef047ad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.create_index('ix_posts_author_id', 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_category', 'posts', ['category'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.create_index('ix_votes_post_id', 'votes', ['post_id'], unique=False)
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_user_id', table_name='votes')
    op.drop_index('ix_votes_post_id', table_name='votes')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_category', table_name='posts')
    op.drop_index('ix_posts_author_id', table_name='posts')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'is_published')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    # ### end Alembic commands ###
